version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - PORT=4000
      - JWT_SECRET=dev-secret-change-me
      - DATABASE_URL=file:./dev.db
    ports:
      - "4000:4000"
    volumes:
      - db-data:/app/dev.db
    working_dir: /app

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "5174:5174"
    depends_on:
      - backend

volumes:
  db-data:


